name: acunetix_scan_job
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Starts actions with given inputs
      - name: Start Acunetix 360 Scan
        uses: Acunetix360/Acunetix-360-GitHub-Actions@v0.0.1
        id: acunetix-360-scan-step
        with:
          website-id: '0591362d-9c97-42f4-1e53-af9304493940'
          scan-type: 'FullWithPrimaryProfile'
          profile-id: '00000000-0000-0000-0000-000000000000'
          user-id: ${{ secrets.ACUNETIX_USER_ID }}
          api-token: ${{ secrets.ACUNETIX_API_TOKEN }}
          base-url: 'http://52.161.96.86'
      # Displays output for action
      - name: Display Scan Request Message
        run: echo "${{ steps.acunetix-360-scan-step.outputs.scan-message }}"
